Revert XSPICE enablement - requires flex
XSPICE requires flex (lexical analyzer) to generate ifs_lex.c and mod_lex.c
for the code model preprocessor (cmpp). Flex is not available in the build
environment, causing build failures.

Error: fatal error: ifs_lex.c: No such file or directory

Reverts previous commit and documents why XSPICE cannot be enabled.
Addresses https://github.com/pyodide/pyodide-recipes/issues/373